name: build and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: build and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y cmake g++
    - name: configure
      run: mkdir -p build && cd build && cmake .. -DBUILD_TESTING=ON
    - name: build
      run: cd build && make --jobs=8
    - name: test
      run: cd build && make test
